spring:
  application:
    name: spring_oauth

  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: spring_oauth

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Open
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs